# Generated by Django 4.1.5 on 2023-02-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_product', models.ImageField(null=True, upload_to='imagen')),
                ('name_product', models.CharField(max_length=200)),
                ('description_product', models.TextField()),
                ('pub_date_product', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
