# Generated by Django 4.1.5 on 2023-02-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen1', models.ImageField(null=True, upload_to='equipos')),
                ('imagen2', models.ImageField(null=True, upload_to='equipos')),
                ('imagen3', models.ImageField(null=True, upload_to='equipos')),
                ('imagen4', models.ImageField(null=True, upload_to='equipos')),
                ('imagen5', models.ImageField(null=True, upload_to='equipos')),
                ('descripcion', models.CharField(max_length=500)),
                ('fechaPublicacion', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
